export const products = [
    {
      id: 1,
      title_ar: "نوافذ ألمنيوم",
      title_en: "Aluminum Windows",
      description_ar: "نوافذ ألمنيوم عالية الجودة بتصاميم مختلفة تناسب جميع الاحتياجات.",
      description_en: "High-quality aluminum windows with various designs to suit all needs.",
      image: "/our_products/Al-windows.png?height=600&width=800",
      slug: "aluminum-windows",
    },
    {
      id: 2,
      title_ar: "أبواب ألمنيوم",
      title_en: "Aluminum Doors",
      description_ar: "أبواب ألمنيوم متينة وعصرية بمقاسات وتصاميم متنوعة.",
      description_en: "Durable and modern aluminum doors with various sizes and designs.",
      image: "/our_products/Al-doors.jpg?height=600&width=800",
      slug: "aluminum-doors",
    },
    {
      id: 3,
      title_ar: "واجهات زجاجية",
      title_en: "Glass Facades",
      description_ar: "واجهات زجاجية أنيقة مصنوعة من أفضل أنواع الألمنيوم والزجاج.",
      description_en: "Elegant glass facades made from the best types of aluminum and glass.",
      image: "/our_products/Al-Glass-Facades.jpg?height=600&width=800",
      slug: "glass-facades",
    },
    {
      id: 4,
      title_ar: "مطابخ ألمنيوم",
      title_en: "Aluminum Kitchens",
      description_ar: "مطابخ ألمنيوم عصرية وعملية بتصاميم مختلفة.",
      description_en: "Modern and practical aluminum kitchens with various designs.",
      image: "/our_products/Al-kitchen.webp?height=600&width=800",
      slug: "aluminum-kitchens",
    },
    {
      id: 5,
      title_ar: "درابزينات",
      title_en: "Railings",
      description_ar: "درابزينات ألمنيوم أنيقة ومتينة للشرفات والسلالم.",
      description_en: "Elegant and durable aluminum railings for balconies and stairs.",
      image: "/our_products/Al-stairs.jpg?height=600&width=800",
      slug: "railings",
    },
    {
      id: 6,
      title_ar: "قواطع ألمنيوم",
      title_en: "Aluminum Partitions",
      description_ar: "قواطع ألمنيوم للمكاتب والمساحات التجارية.",
      description_en: "Aluminum partitions for offices and commercial spaces.",
      image: "/our_products/Al-partitions.webp?height=600&width=800",
      slug: "aluminum-partitions",
    },
  ]
